### ISSUE TITLE
[Feature Request] 能否加入双击单选框功能

### ISSUE THREAD

**Issue by Hipd** [benzBrake/Firefox-downloadPlus.uc.js#1]
以前用过一个脚本，可以双击单选框或者后面的文字，直接触发相应功能。希望这个脚本也可以加入这个功能，相信效率会提高很多。谢谢！

**Comment by benzBrake** [comment]
不是很懂什么意思

**Comment by Hipd** [comment]
> 

现在的保存窗口有“打开”或者“保存”两个选项，如果要使用某个选项，需要先单击单选框，然后点击确定按钮。

我的提议（以前有其他人的脚本实现过此功能）是直接双击上面的“打开”或者“保存”选项文本或单选框，立即执行相应命令，就不用再点击下方的”确定”按钮了，可以提高效率。
