### ISSUE TITLE
Firefox 119.0 Cannot use

### ISSUE THREAD

**Issue by laulguo** [benzBrake/Firefox-downloadPlus.uc.js#2]
浏览器版本号

119.0

你在用什么 UC 环境(引导器)

alice0775/xiaoxiaoflood
均可以复刻

[downloadPlus_ff98.uc.js](https://github.com/benzBrake/Firefox-downloadPlus.uc.js/blob/56431dcd7cce98239d2f2e85f1cf306888be6926/downloadPlus_ff98.uc.js)

![3](https://github.com/benzBrake/Firefox-downloadPlus.uc.js/assets/38545281/ac53e3de-f264-462d-98a2-783afdf9291d)

**Comment by benzBrake** [comment]
哈哈抱歉，那个链接过去的还是老版本，我下次改成说明文字免得误导你们

**Comment by laulguo** [comment]
> 哈哈抱歉，那个链接过去的还是老版本，我下次改成说明文字免得误导你们

我也是看着看着发现新版本大了很多，于是自己关掉了
