### ISSUE TITLE
"FlashGot" radio button above "Save File" one

### ISSUE THREAD

**Issue by robbely** [benzBrake/Firefox-downloadPlus.uc.js#3]
In the picture you have on the main page, it looks like you have "Save File" at the bottom, but I have "FlashGot" at the bottom in the radio button list.

Is it possible for me to move the "Save File" entry to the bottom (like with the original FlashGot addon) or just below "Open With"?

**Comment by benzBrake** [comment]
Using css to rearrange it
```
@-moz-document url-prefix("chrome://mozapps/content/downloads/unknownContentType.x") {
    #save {
        order: 9;
    }
}
```

**Comment by robbely** [comment]
Many thanks for the quick reply - it worked :)

**Comment by robbely** [comment]
Apologies, I have xiaoxiaflood's DownTheAll addon - is it possible to move FlashGot above the DTA radio buttons - ie directly below "Open With"?

**Comment by robbely** [comment]
NVM I was able to achieve it by moving downthemall down instead :)

```
@-moz-document url-prefix("chrome://mozapps/content/downloads/unknownContentType.x") {
    #save {
        order: 9;
    }
    #downthemallcontainer {
        order: 8;
    }
}
```
